name: GCloud Auth Setup
description: Authenticates with Google Cloud and sets up gcloud CLI
inputs:
  credentials_json:
    required: true
    description: Service account credentials JSON
  project_id:
    required: true
    description: GCP Project ID

runs:
  using: "composite"
  steps:
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.credentials_json }}
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ inputs.project_id }}
