# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Deploy on PR Merge

on:
  push:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: GCloud Auth Setup
      uses: ./.github/actions/gcloud-auth
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_SA }}
        project_id: ${{ vars.GCP_AIRFLOW_PROJECT_ID }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.in ]; then
          pip install -r requirements.in;
        else
          echo "No requirement found!"
        fi
    - name: Build project python package
      run: |
        python -m build
